language: python
python:
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install pytest pytest-cov pytest_httpx pytest-asyncio httpx uvicorn fastapi first
script:
  - cd ./src
  - pytest